apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEAUaDCv+Xr71/NCnL+DJSiLVAZIOcxLFj23tMoy8xPBuH8jyluMd2TvtZcggQ8utZCx2T/U4/f97ufr1ZWo5C1BWBevPJ4OGO+sFw7vP6bDunkxlLfBuEwTFKxZLdulDpMCsGY3nakTjCV/cOsJ74ni6jeUagwlygARWfa1ZefyETIrG+RXJFJGa+0ujxcpb34933HmXqDK2k3lpsNMRAKELfRbLdlmuapR+XRRanSjUciHFE2DgCC7OwN2Gz1GEfGLaFmeOwGzNESs0R116Vy3xAIEW90bgBpPxAakXaGGUbAcE4/14oyjTxfacBjItwqcM9GpJuKETSbZbW4HOq6c4UyutbtBfwFXgxEmJ2Ib4mMCPp5zXdvsUGO08