apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEDQaDKPhSJsgIpiwCEj73CLVAUK/ZaBFq7odHnBuyQSiuOpemOaItiKj4BDqF0bKiyTS580Qj3es1lVpcsH5axv7qAx5WXFdlGoDCaPS1U6dAh9X78qutslzzvi5D+FXydAAjVbSpWpP/7av/zZHK94s/qkQuFCt8YUD+PjUvjvwOnOx4aocVdBG/HJblHQi2kd9Wn03Xy8QyzUlOQC68PRs2/0sHWy+9SiSVyjm8vb57EZFYtea4RPOtjH6w88Q+KcG6cG9ZVBrwxU5eUtuyhaxFw4iK3BGcVNWHcdXSo4CFUgPmXtkGijngIGdBjItPh2KptqUe2leiltPAP0cuwr0f82lTGq1zWMgdGN2INll+e9MPakmZYdUIxQY