apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEJz//////////wEaDMXVqeLgUBJKX/pFwyLVAXlH/OFeWTp+gdyLoVhWDWDBUlZzjWbwC5b9rU5zba8TzWwqeIEPlKgFr7mFJPLe09yKQ1F5a3OOgXvHvenwlVzEd8E2qocvTNtehr9xqFZLn/bf9pAmaSJGBhItr/MnIjUs2IwEyTkhxGxTW+0dUiQqlA3ZksJwXrlh5oq1TS5MXxWe3pLgafYyjZ/I34AgxdNyg8xGswa2WJ9apNn+N28UUrX7cBym3Ai60Q9JofG5mjMc++k3GmUlo6T4h/k2LN5gJ2kH02+xMnOsSKOsUSDuGjpJUCju0t+cBjItbdfh9/Ub9sBmG+2VXgZbohnsknBx5ZI3r+yyInpnyG9uDQSr4R2L+i6fmi2c