apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEP///////////wEaDCMbfYOSiSpdXqiipSLVATms//qeqxK7DxScDW3OfaG1FMAPQu2nW8BPgUFzFbeuiR9XbBk2+YgKeOxft0wjnv+SGWnh2O/2DkuhhmoYiRljBmvXfh9DtBPQfuU0JfsxzqOr3pFKTyQPCRvJ8crChlv5ZvNFuZd0A6+oflqVxdRnzwv1Yv+WAND4A5gzcvf8CDSoh4Beb6yWL+TEtW11m0VkbvYCqP833ly0MJ82ltHMrpf58eSJVNriD/MmuSmRYDtesEQt4APj4HFDkbOb+WiBwOCVpeefYJC1TMoTFLf9jZoTQCicovWcBjItsnnYvy1Hg1hPvqL/NheNsWIKEkJ3I3Baus4Wx1GO0c4JWpO0xoLdHQr5abhH